videos_dir_path: ./sample_project/videos # eventually: \processed\LondonZoo\jewel-wasp_Ampulex-compressa\DLC_femaleandmale\jwasp_femaleandmale-Sanna-2022-09-12
metadata_fields_file_path: ./sample_project/metadata_fields.yaml
metadata_key_field_str: File
pose_estimation_results_path: ./sample_project/pose_estimation_results
