videos_dir_path: ./sample_project/videos
metadata_fields_file_path: ./sample_project/metadata_fields.yaml
metadata_key_field_str: File
pose_estimation_model_str: DLC_resnet50_jwasp_femaleandmaleSep12shuffle1_1000000
pose_estimation_results_path: ./sample_project/pose_estimation_results
roi_names:
  - "enclosure"
  - "left_box"
  - "top_box"
  - "right_box"
  - "bottom_box"
  - "tube"
