name: 'publish docs'

# Publish when upon push to main or add-docs branches
on:
  push:
    branches:
      - main
      - add-docs
    tags:
      - '*'

jobs:
  publish_sphinx_docs:
    name: Publish Sphinx Docs
    runs-on: ubuntu-latest
    steps:
    - uses: neuroinformatics-unit/actions/publish_sphinx_docs@v1
      with:
        secret_input: ${{ secrets.GITHUB_TOKEN }}
